### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by SanekoGato** [lachwright/derp#1]
- [x] Rot-Sprite changes

- [x] "Roll-Holes" working

- [x] Ear Separation fixes

- [x] Import new bounce frames

- [x] GFZ1 ear softlock bug-fix (https://cdn.discordapp.com/attachments/504410752975896597/700078184258863155/srb20092.gif)

- [x] Others collecting your own ear bug-fix (https://cdn.discordapp.com/attachments/504410752975896597/700081881663930408/srb20093.gif)

- [x] Aerial ear throw bug-fix

- [x] Other ear-related bugs (https://cdn.discordapp.com/attachments/504410752975896597/695651598176747570/srb20007.gif and https://cdn.discordapp.com/attachments/504410752975896597/695653344131153980/srb20008.gif)

- [x] Add command toggle for pose variations

- [x] Have thrown ears knock other players back

- [x] Fix boomearang spawning on top of walls
