### ISSUE TITLE
Derp v2 Update Ideas/Checklist

### ISSUE THREAD

**Issue by SanekoGato** [lachwright/derp#2]
- [ ] Add new secrets

- [ ] Add more poses

- [ ] Fix HURT-frame-forcing waterfalls giving back bounce under special circumstances

- [ ] Fix ringslinger related bugs, ( hitting someone with ear makes receiving player lose points. )

- [ ] Secondcolor Support!

- [ ] Hats! ( maybe )

- [ ] Fix ear not appearing on multiplayer char-select ( maybe )

- [ ] Be able to hold spin for first hit of boomearang

- [ ] Other bugs that I didn't catch
